application/modules/admin/welcome/routes.py
from flask_login import login_required
from application import app, mongo, role_required
from flask import Blueprint, render_template, url_for

admin_welcome = Blueprint('admin_welcome', __name__, url_prefix='/admin/welcome')

@admin_welcome.route('/', methods=["GET"])
@role_required(["admin","visitor"])
def index():
    return render_template('admin/welcome.html')

application/modules/gugurgunung/routes.py
import os, glob, re, pymongo
from html.parser import HTMLParser
from math import ceil
from bson.objectid import ObjectId
from application import app, mongo
from application.helpers import forms
from flask import Blueprint, render_template, redirect, url_for, request, flash, jsonify
from flask_login import current_user
from datetime import datetime

gugurgunung = Blueprint('gugurgunung', __name__, url_prefix='/gugurgunung')


@gugurgunung.route('/', methods=["GET","POST"])
def index():
    if request.method == "GET":
        for x in glob.glob('application/static/img/headers/lumbungilmu.*'):
            header_image = url_for('static', filename=x)
        header_image = header_image.split('/')[-1:][0]
        header_image = url_for('static', filename="img/headers/"+header_image)
        article = mongo.db.articles.find({"is_active":True,"category":{'$exists':False}}).sort("created_at",pymongo.DESCENDING)
        count = article.count()
        article = mongo.db.articles.find({"is_active":True,"category":{'$exists':False}}).sort("created_at",pymongo.DESCENDING).limit(4)
        articles = []
        for x in article:
            x["thumbnail"] = url_for('static', filename="img/articles/"+x["thumbnail"])
            x["content"] = re.compile(r'<[^>]+>').sub('',x["content"])
            articles.append(x)
        return render_template('gugurgunung.html', header_image=header_image, articles=articles, current_page=1, pages=ceil(count/4))
    else:
        for x in glob.glob('application/static/img/headers/lumbungilmu.*'):
            header_image = url_for('static', filename=x)
        header_image = header_image.split('/')[-1:][0]
        header_image = url_for('static', filename="img/headers/"+header_image)
        search = str(request.form["search"])

        rgx = re.compile('.*'+search+'.*', re.IGNORECASE)
        article = mongo.db.articles.find({"is_active": True, "category": {'$exists': False},"judul":rgx}).sort("created_at",pymongo.DESCENDING)
        count = article.count()
        article = mongo.db.articles.find({"is_active": True, "category": {'$exists': False},"judul":rgx}).sort("created_at",pymongo.DESCENDING).limit(4)
        articles = []
        for x in article:
            x["thumbnail"] = url_for('static', filename="img/articles/"+x["thumbnail"])
            x["content"] = re.compile(r'<[^>]+>').sub('',x["content"])
            articles.append(x)
        return render_template('gugurgunung.html', keyword=search, header_image=header_image, articles=articles, current_page=1, pages=ceil(count/4))

application/modules/lumbungilmu/routes.py
import os, glob, re, pymongo, html_sanitizer
from html.parser import HTMLParser
from math import ceil
from bson.objectid import ObjectId
from application import app, mongo
from application.helpers import forms
from flask import Blueprint, render_template, redirect, url_for, request, flash, jsonify
from flask_login import current_user
from datetime import datetime

lumbungilmu = Blueprint('lumbungilmu', __name__, url_prefix='/lumbungilmu')

@lumbungilmu.route('/', methods=["GET","POST"])
def index():
    if request.method == "GET":
        for x in glob.glob('application/static/img/headers/lumbungilmu.*'):
            header_image = url_for('static', filename=x)
        header_image = header_image.split('/')[-1:][0]
        header_image = url_for('static', filename="img/headers/"+header_image)
        article = mongo.db.articles.find({"is_active":True,"category":{'$exists':True}}).sort("created_at",pymongo.DESCENDING)
        newes = mongo.db.articles.find({"is_active":True,"category":{'$exists':True}}).sort("created_at", pymongo.DESCENDING).limit(3)
        newest = []
        for x in newes:
            x["thumbnail"] = url_for('static', filename="img/articles/" + x["thumbnail"])
            x["content"] = re.compile(r'<[^>]+>').sub('', x["content"])
            newest.append(x)
        pipeline = [{"$sort":{"count":1}},{"$limit":5},{"$group": {"_id": "$article", "count": {"$sum": 1}}}]
        pop = mongo.db.statistics.aggregate(pipeline)
        popular = []
        for x in pop:
            pop_art = mongo.db.articles.find_one({"_id": ObjectId(x["_id"])})
            try:
                pop_art["category"]
            except KeyError:
                pass
            else:
                pop_art["thumbnail"] = url_for('static', filename="img/articles/" + pop_art["thumbnail"])
                pop_art["content"] = re.compile(r'<[^>]+>').sub('', pop_art["content"])
                popular.append(pop_art)
        article = mongo.db.articles.find({"is_active":True,"category":{'$exists':True}}).sort("created_at",pymongo.DESCENDING).limit(4)
        articles = []
        for x in article:
            category = mongo.db.categories.find_one({"_id": ObjectId(x["category"])})
            x["category_name"] = category["category"]
            x["thumbnail"] = url_for('static', filename="img/articles/"+x["thumbnail"])
            x["content"] = re.compile(r'<[^>]+>').sub('',x["content"])
            articles.append(x)
        count = article.count()
        return render_template('lumbungilmu.html', newest=newest, popular=popular, header_image=header_image, articles=articles, current_page=1, pages=ceil(count/4))
    else:
        for x in glob.glob('application/static/img/headers/lumbungilmu.*'):
            header_image = url_for('static', filename=x)
        header_image = header_image.split('/')[-1:][0]
        header_image = url_for('static', filename="img/headers/"+header_image)
        search = str(request.form["search"])

        rgx = re.compile('.*'+search+'.*', re.IGNORECASE)
        article = mongo.db.articles.find({"is_active": True, "category": {'$exists': True},"judul":rgx}).sort("created_at",pymongo.DESCENDING)
        newes = mongo.db.articles.find({"is_active": True, "category": {'$exists': True}}).sort("created_at", pymongo.DESCENDING).limit(3)
        newest = []
        for x in newes:
            x["thumbnail"] = url_for('static', filename="img/articles/" + x["thumbnail"])
            x["content"] = re.compile(r'<[^>]+>').sub('', x["content"])
            newest.append(x)
        pipeline = [{"$sort":{"count":1}},{"$limit":5},{"$group": {"_id": "$article", "count": {"$sum": 1}}}]
        pop = mongo.db.statistics.aggregate(pipeline)
        popular = []
        for x in pop:
            pop_art = mongo.db.articles.find_one({"_id": ObjectId(x["_id"])})
            try:
                pop_art["category"]
            except KeyError:
                pass
            else:
                pop_art["thumbnail"] = url_for('static', filename="img/articles/" + pop_art["thumbnail"])
                pop_art["content"] = re.compile(r'<[^>]+>').sub('', pop_art["content"])
                popular.append(pop_art)
        article = mongo.db.articles.find({"is_active": True, "category": {'$exists': True},"judul":rgx}).sort("created_at",pymongo.DESCENDING).limit(4)
        articles = []
        for x in article:
            category = mongo.db.categories.find_one({"_id": ObjectId(x["category"])})
            x["category_name"] = category["category"]
            x["thumbnail"] = url_for('static', filename="img/articles/"+x["thumbnail"])
            x["content"] = re.compile(r'<[^>]+>').sub('',x["content"])
            articles.append(x)
        count = article.count()
        return render_template('lumbungilmu.html', newest=newest, popular=popular, keyword=search, header_image=header_image, articles=articles, current_page=1, pages=ceil(count/4))

@lumbungilmu.route('/<int:page>', methods=["GET"], defaults={"keyword":""})
@lumbungilmu.route('/<string:keyword>/<int:page>', methods=["GET"])
def search(keyword,page):
    for x in glob.glob('application/static/img/headers/lumbungilmu.*'):
        header_image = url_for('static', filename=x)
    header_image = header_image.split('/')[-1:][0]
    header_image = url_for('static', filename="img/headers/" + header_image)
    search = keyword
    rgx = re.compile('.*' + search + '.*', re.IGNORECASE)
    article = mongo.db.articles.find({"is_active": True, "judul": rgx}).sort("created_at",pymongo.DESCENDING)
    newes = mongo.db.articles.find({"is_active": True, "category": {'$exists': True}}).sort("created_at",
                                                                                            pymongo.DESCENDING).limit(3)
    newest = []
    for x in newes:
        print(x["judul"])
        x["thumbnail"] = url_for('static', filename="img/articles/" + x["thumbnail"])
        x["content"] = re.compile(r'<[^>]+>').sub('', x["content"])
        newest.append(x)
    pipeline = [{"$sort":{"count":1}},{"$limit":5},{"$group": {"_id": "$article", "count": {"$sum": 1}}}]
    pop = mongo.db.statistics.aggregate(pipeline)
    popular = []
    for x in pop:
        pop_art = mongo.db.articles.find_one({"_id": ObjectId(x["_id"])})
        pop_art["thumbnail"] = url_for('static', filename="img/articles/" + pop_art["thumbnail"])
        pop_art["content"] = re.compile(r'<[^>]+>').sub('', pop_art["content"])
        popular.append(pop_art)
    for x in newest:
        x["thumbnail"] = url_for('static', filename="img/articles/"+x["thumbnail"])
        x["content"] = re.compile(r'<[^>]+>').sub('', x["content"])
    if page > 1:
        # article = mongo.db.articles.find({"is_active": True, "judul": rgx}).sort("created_at",pymongo.DESCENDING).skip(4*(page-1)).limit(4)
        article = mongo.db.articles.find({"is_active": True, "category": {'$exists': True}, "judul": rgx}).sort(
            "created_at", pymongo.DESCENDING).skip(4*(page-1)).limit(4)
    else:
        article = mongo.db.articles.find({"is_active": True, "category": {'$exists': True}, "judul": rgx}).sort(
            "created_at", pymongo.DESCENDING).limit(4)
    articles = []
    for x in article:
        category = mongo.db.categories.find_one({"_id": ObjectId(x["category"])})
        x["category_name"] = category["category"]
        x["thumbnail"] = url_for('static', filename="img/articles/" + x["thumbnail"])
        x["content"] = re.compile(r'<[^>]+>').sub('', x["content"])
        articles.append(x)
    count = article.count()
    return render_template('lumbungilmu.html', keyword=search, header_image=header_image, articles=articles,
                           current_page=page, pages=ceil(count / 4), newest=newest, popular=popular)

@lumbungilmu.route('/detail/<string:slug>', methods=["GET"])
def detail(slug):
    article = mongo.db.articles.find_one({"is_active":True,"slug":slug})
    counter = mongo.db.statistics.insert_one({"article":ObjectId(article["_id"]),"viewed_at":datetime.now()})
    newes = mongo.db.articles.find({"is_active": True, "category": {'$exists': True}}).sort("created_at",
                                                                                            pymongo.DESCENDING).limit(3)
    newest = []
    for x in newes:
        x["thumbnail"] = url_for('static', filename="img/articles/" + x["thumbnail"])
        x["content"] = re.compile(r'<[^>]+>').sub('', x["content"])
        newest.append(x)
    pipeline = [{"$sort": {"count": 1}},{"$limit":5}, {"$group": {"_id": "$article", "count": {"$sum": 1}}}]
    pop = mongo.db.statistics.aggregate(pipeline)
    popular = []
    for x in pop:
        pop_art = mongo.db.articles.find_one({"_id": ObjectId(x["_id"])})
        try:
            pop_art["category"]
        except KeyError:
            pass
        else:
            pop_art["thumbnail"] = url_for('static', filename="img/articles/" + pop_art["thumbnail"])
            pop_art["content"] = re.compile(r'<[^>]+>').sub('', pop_art["content"])
            popular.append(pop_art)
    try:
        article["category"]
    except:
        article["category_name"] = "Gugur Gunung"
    else:
        category = mongo.db.categories.find_one({"_id": ObjectId(article["category"])})
        article["category_name"] = category["category"]
    article["thumbnail"] = url_for('static', filename="img/articles/" + article["thumbnail"])
    if os.path.isfile("application"+url_for('static', filename="infographics/"+article["slug"]+".pdf")):
        article["infographic"] = url_for('static', filename="infographics/"+article["slug"]+".pdf")
    else:
        article["infographic"] = None
    author = mongo.db.users.find_one({"_id":ObjectId(article["author"])})
    if author["role"] != "admin":
        author = mongo.db.visitors.find_one({"_id":ObjectId(author["visitor_id"])})
        author["avatar_url"] = url_for('static', filename="img/avatar/" + author["avatar_url"])
    else:

application/modules/pedati/routes.py
import os,glob, re
from bson.objectid import ObjectId
from application import app, mongo
from flask import Blueprint, render_template, url_for, request, current_app

pedati = Blueprint('pedati', __name__, url_prefix='/pedati')

@pedati.route('/', methods=["GET"])
def index():
    for x in glob.glob('application/static/img/headers/pedati.*'):
        header_image = url_for('static', filename=x)
    header_image = header_image.split('/')[-1:][0]
    header_image = url_for('static', filename="img/headers/"+header_image)
    header1 = mongo.db.contents.find_one({"module": "pedati", "element": "header1"})["data"]
    header2 = mongo.db.contents.find_one({"module": "pedati", "element": "header2"})["data"]
    teams = mongo.db.contents.find_one({"module": "pedati", "element": "teams"})["data"]
    for x in teams:
        x["avatar_url"] = url_for('static', filename="img/team/"+x["avatar_url"])
    visitor = mongo.db.users.find({"role":"visitor","is_contrib":True}).limit(4)
    contributors = []
    for x in visitor:
        detail = mongo.db.visitors.find_one({"_id":ObjectId(x["visitor_id"])})
        detail["avatar_url"] = url_for('static', filename="img/avatar/"+detail["avatar_url"])
        detail["email"] = x["email"]
        social = []
        if detail["facebook"] != "" and detail["facebook"] != '' and detail["facebook"] != None:
            social.append({"type": "facebook", "url": detail["facebook"]})
        if detail["twitter"] != "" and detail["twitter"] != '' and detail["twitter"] != None:
            social.append({"type": "twitter", "url": detail["twitter"]})
        if detail["instagram"] != "" and detail["instagram"] != '' and detail["instagram"] != None:
            social.append({"type": "instagram", "url": detail["instagram"]})
        if detail["linkedin"] != "" and detail["linkedin"] != '' and detail["linkedin"] != None:
            social.append({"type": "linkedin", "url": detail["linkedin"]})
        detail["social"] = social
        contributors.append(detail)
    current_app.logger.info(teams)
    return render_template('pedati.html', header1=header1, header2=header2, teams=teams, header_image=header_image, contributors=contributors)

@pedati.route('/contributors', methods=["GET","POST"])
def contributors():
    if request.method == "GET":
        visitor = mongo.db.users.find({"role":"visitor","is_contrib":True})
    else:
        search = str(request.form["search"])
        rgx = re.compile('.*' + search + '.*', re.IGNORECASE)
        visitor = mongo.db.users.find({"role": "visitor", "is_contrib": True,"username":rgx})
    for x in glob.glob('application/static/img/headers/pedati.*'):
        header_image = url_for('static', filename=x)
    header_image = header_image.split('/')[-1:][0]
    header_image = url_for('static', filename="img/headers/"+header_image)
    contributors = []
    for x in visitor:
        detail = mongo.db.visitors.find_one({"_id":ObjectId(x["visitor_id"])})
        detail["avatar_url"] = url_for('static', filename="img/avatar/"+detail["avatar_url"])
        detail["email"] = x["email"]
        print(detail)
        social = []
        if detail["facebook"] != "" and detail["facebook"] != '' and detail["facebook"] != None:
            social.append({"type": "facebook", "url": detail["facebook"]})
        if detail["twitter"] != "" and detail["twitter"] != '' and detail["twitter"] != None:
            social.append({"type": "twitter", "url": detail["twitter"]})
        if detail["instagram"] != "" and detail["instagram"] != '' and detail["instagram"] != None:
            social.append({"type": "instagram", "url": detail["instagram"]})
        if detail["linkedin"] != "" and detail["linkedin"] != '' and detail["linkedin"] != None:
            social.append({"type": "linkedin", "url": detail["linkedin"]})
        detail["social"] = social
        contributors.append(detail)
    print(contributors)
    return render_template('contributors.html', header_image=header_image, contributors=contributors)

application/templates/contributors.html
{% extends 'base.html'%}
{% block title %}
    <title>Lumbung Tani | contributors</title>
{% endblock %}

{% block css %}
    <style>
        .table th, .table td{
            border: 0px solid #dee2e6;
        }
    </style>
{% endblock %}

{% block content %}
    <header style="background-image: url('{{ header_image }}'); background-size: cover; background-position: center; background-repeat: no-repeat; width: 100%; height: 350px; opacity: 0.6">
    </header>
    <section class="background-gray why-should" style="padding: 20px;">
        <div class="container mt-5">
            <div class="row justify-content-md-center mb-4 mt-5">
                <div class="col-md-6 text-center">
                    <h1 class="color-dark-title">List Semua Kontributor</h1>
                    Lorem ipsum dolor sit, amet consectetur adipisicing elit. Cumque recusandae eum repudiandae qui quisquam quae.
                </div>
            </div>
            <div class="row">
                <div class="col-md-8"></div>
                <div class="col-md-4">
                    <div class="dt-search mt-4 mb-3">
                                                    <form method="post" action="{{ url_for('pedati.contributors') }}">
                        <div class="dt-search-box">

                                <div class="search-field">
                                    <input type="text" name="search" class="search-input" placeholder="Cari nama kontributor">
                                </div>
                                <div class="search-button">
                                    <button type="submit" class="btn btn-primary btn-search">
                                        <i class="fa fa-search"></i>
                                    </button>
                                </div>
                        </div>
                            </form>

                    </div>
                </div>
            </div>
            <div class="modern-table-boxed">
                {% for contrib in contributors %}
                    <div class="d-table-row">
                        <div class="d-table-cell">
                            <div class="company-logo" style="background-image: url('{{ contrib.avatar_url }}'), url('{{ url_for('static', filename="img/avatar/user_default.png") }}'); border-radius: 50px;"></div>
                        </div>
                        <div class="d-table-cell">
                            {{ contrib.fullname }}
                        </div>
                        <div class="d-table-cell">
                            {{ contrib.jabatan }}
                        </div>
                        <div class="d-table-cell">
                            {{ contrib.email }}
                        </div>
                        <div class="d-table-cell shrink">
                            <a href="javascript:void(0)" data-toggle="modal" id="trigger-kontrib-detail" data-target="#viewDetailModal" data-item-id="{{ loop.index }}" data-name="{{ contrib.fullname }}" data-email="{{ contrib.email }}" data-hp="{{ contrib.phone }}" data-jabatan="{{ contrib.jabatan }}" data-social='{% for x in contrib.social %}{{ x.type }}={{ x.url }}|{% endfor %}' class="btn btn-primary">
                                Lihat Detail
                            </a>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </section>

    <!-- MODAL -->
    <div class="modal" id="viewDetailModal">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div class="modal-body">
                    <h4>
                        Detail <span class="text-green-logo" id="modal-contrib-name-header"></span>
                    </h4>
                    <div class="data-modal-content mt-5">
                        <table class="table table-striped">
                            <tr>
                                <td style="width: 150px;">Email</td>
                                <td style="width: 10px;">:</td>
                                <td id="modal-contrib-email"></td>
                            </tr>
                            <tr>
                                <td>Jabatan</td>
                                <td>:</td>
                                <td id="modal-contrib-jabatan"></td>
                            </tr>
                            <tr>
                                <td>Social Media</td>
                                <td>:</td>
                                <td>
                                    <div class="d-flex" id="modal-contrib-social">
                                    </div>
                                </td>
                            </tr>
                        </table>
                    </div>
                    <div class="mt-3 text-center">
                        <a href="javascript:void(0)" class="btn btn-primary" data-dismiss="modal">Close</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block js %}
    <script>
        $(document).on('click','#trigger-kontrib-detail',function () {
            $("#modal-contrib-social").html(""); // buat clear list sosial media di modals

                $('#modal-contrib-email').html($(this).data('email')); // buat ngeset email di modals
                $('#modal-contrib-jabatan').html($(this).data('jabatan')); // buat ngeset jabatan di modals
                $('#modal-contrib-name-header').html($(this).data('name'));
                $('#modal-contrib-phone').html($(this).data('hp'));
                var socials = $(this).data('social'); // ambil data social media yang dimiliki user terpilih
                if (socials.length > 0){
                    socials = socials.slice(0,-1); // pre-processing data
                    var arr = socials.split('|'); // pre-processing data
                    arr.forEach(function (a) {
                        a = a.split('='); // pre-processing data
                        $("#modal-contrib-social").append("<a href='"+a[1]+"' target='_blank'><div class='social-box "+a[0]+" mr-2'><i class='fa fa-"+a[0]+"'></i></div></a>"); // nambahin sosial medianya
                    })
                } else {
                    $("#modal-contrib-social").append("-")
                }
            });

            $('#myCarousel').carousel({
                interval: 0
            })

            $('.carousel .carousel-item').each(function() {
                var minPerSlide = 4;
                var next = $(this).next();
                if (!next.length) {
                    next = $(this).siblings(':first');
                }
                next.children(':first-child').clone().appendTo($(this));

                for (var i = 0; i < minPerSlide; i++) {
                    next = next.next();
                    if (!next.length) {
                        next = $(this).siblings(':first');
                    }

                    next.children(':first-child').clone().appendTo($(this));
                }
            });
        </script>
</html>
{% endblock %}

application/templates/gugurgunung.html
{% set active_page = 'gugurgunung' %}
{% extends 'base.html' %}

{% block title %}
    <title>Lumbung Tani | Gugur Gunung</title>
{% endblock %}

{% block css %}
        <style>
            .myAlert-top{
                top: 5px;
                left:2%;
                width: auto;
            }
        </style>
{% endblock %}

{% block content %}
    {% with messages = get_flashed_messages(with_categories=True) %}
      {% if messages %}
            <div class="myAlert-top alert alert-{{ messages[0][0] }}">
            <a href="#" class="close" data-dismiss="alert" aria-label="close">x</a>
            {% for message in messages %}
                {% for key, value in message[1].items() %}
                    <strong>{{ key }} :</strong> {{ value }}<br>
                {% endfor %}
            {% endfor %}
            </div>
      {% endif %}
    {% endwith %}
    <header style="background-image: url('{{ url_for('static', filename='img/1.jpeg') }}'); background-size: cover; background-position: center; background-repeat: no-repeat; width: 100%; height: 350px; opacity: 0.6">
    </header>
    <section class="background-gray why-should" style="padding: 20px">
        <div class="container">
            <h1>Gugur Gunung</h1>
            <div class="short-separator"></div>
            <form method="post" action="{{ url_for('gugurgunung.index') }}">
                <div class="blog-layout row">
                    <div class="sidebar-body col-md-12">
                        <div class="row">
                            <div class="col-md-6">
                                <div class="dt-search mt-4">
                                    <div class="dt-search-box">
                                        <div class="search-field">
                                            <input type="text" name="search" class="search-input" placeholder="Cari nama artikel" value="{{ keyword }}">
                                        </div>
                                        <div class="search-button">
                                            <button type="submit" class="btn btn-primary btn-search">
                                                <i class="fa fa-search"></i>
                                            </button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        {% if articles|length != 0 %}
                            {% for article in articles %}
                                <div class="article-container">
                                    <div class="article-list">
                                        <div class="row">
                                            <div class="col-md-4 mt-3">
                                                <div class="article-photo" style="background-image: url('{{ article.thumbnail }}')">
                                                </div>
                                            </div>
                                            <div class="col-md-8 mt-3">
                                                <div class="article-detail">
                                                    <div class="d-flex">
                                                        <div>
                                                            <small class="text-green-logo fw-medium">
                                                                {{ article.category_name }}
                                                            </small>
                                                        </div>
                                                        <div class="ml-auto">
                                                            <div class="author">
                                                                {{ article.created_at.strftime('%d %b %Y') }}
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <div class="title mt-1">
                                                        <a href="{{ url_for('lumbungilmu.detail', slug=article.slug) }}">
                                                            {{ article.judul[:56] }}...
                                                        </a>
                                                    </div>
                                                    <p class="description mt-2">
                                                        {{ article.content[:250] }}...
                                                    </p>
                                                    <a href="{{ url_for('lumbungilmu.detail', slug=article.slug) }}" class="btn btn-primary btn-sm mt-2">
                                                        Baca Lebih Lanjut
                                                    </a>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            {% endfor %}
                            <div class="mt-3 mb-4">
                                <ul role="navigation" class="pagination">
                                    <li aria-disabled="true" aria-label="« Previous" class="page-item disabled">
                                        <span aria-hidden="true" class="page-link">
                                            <i class="fa fa-angle-left"></i>
                                        </span>
                                    </li>
                                    {% for x in range(0,pages) %}
                                    <li aria-current="page" class="page-item {% if loop.index == current_page %}active{% endif %} ">
                                        <a href="{% if keyword %} {{ url_for("lumbungilmu.search", keyword=keyword,page=loop.index) }} {% else %} {{ url_for("lumbungilmu.search", page=loop.index) }} {% endif %}"><span class="page-link">{{ loop.index }}</span></a>
                                    </li>
                                    {% endfor %}
                                    <li class="page-item">
                                        <a href="" rel="next" aria-label="Next »" class="page-link">
                                            <i class="fa fa-angle-right"></i>
                                        </a>
                                    </li>
                                </ul>
                            </div>
                        {% else %}
                            <div class="mt-5">
                                <center>
                                    <img src="{{ url_for('static', filename='img/empty.png') }}" style="border-radius: 20px">
                                </center>
                            </div>
                        {% endif %}
                    </div>
                </div>
            </form>
        </div>
    </section>
{% endblock %}

{% block js %}
{% endblock %}